### ISSUE TITLE
Не запускается после сборки проекта

### ISSUE THREAD

**Issue by d-chirkov** [MrMurdock11/empire-cli#5]
```
internal/fs/utils.js:269
    throw err;
    ^

Error: ENOENT: no such file or directory, open 'C:\Users\dchir\Projects\Empire-CLI\dist\providers/../archive/templates.zip'
←[90m    at Object.openSync (fs.js:462:3)←[39m
←[90m    at Object.readFileSync (fs.js:364:35)←[39m
    at new ArchiveProvider (C:\Users\dchir\Projects\Empire-CLI\dist\providers\ArchiveProvider.js:35:58)
    at Object.resolveInstance (C:\Users\dchir\Projects\Empire-CLI\node_modules\←[4minversify←[24m\lib\resolution\instantiation.js:53:18)
    at C:\Users\dchir\Projects\Empire-CLI\node_modules\←[4minversify←[24m\lib\resolution\resolver.js:73:42
    at Array.map (<anonymous>)
    at _injectProperties (C:\Users\dchir\Projects\Empire-CLI\node_modules\←[4minversify←[24m\lib\resolution\instantiation.js:19:57)
    at Object.resolveInstance (C:\Users\dchir\Projects\Empire-CLI\node_modules\←[4minversify←[24m\lib\resolution\instantiation.js:50:18)
    at C:\Users\dchir\Projects\Empire-CLI\node_modules\←[4minversify←[24m\lib\resolution\resolver.js:73:42
    at Object.resolve (C:\Users\dchir\Projects\Empire-CLI\node_modules\←[4minversify←[24m\lib\resolution\resolver.js:97:12) {
  errno: ←[33m-4058←[39m,
  syscall: ←[32m'open'←[39m,
  code: ←[32m'ENOENT'←[39m,
  path: ←[32m'C:\\Users\\dchir\\Projects\\Empire-CLI\\dist\\providers/../archive/templates.zip'←[39m
}
```

Но если скопировать папку archive из src в dist руками, то help выводит

**Comment by MrMurdock11** [comment]
Исправлено в версии пакета "1.0.3".
