### ISSUE TITLE
Не работает создание redux-store

### ISSUE THREAD

**Issue by d-chirkov** [MrMurdock11/empire-cli#6]
```
C:\Users\dchir\Projects\UpAdivce\Apps\UpAdvice.ControlPanel.App\ClientApp\src\store>empire s test
Error: Файл с таким именем отсутствует в архиве.
    at ArchiveProvider.getContentTemplateByFileName (C:\Users\dchir\Projects\Empire-CLI\dist\providers\ArchiveProvider.js:113:19)
    at ArchiveProvider.getActionsContentTemplate (C:\Users\dchir\Projects\Empire-CLI\dist\providers\ArchiveProvider.js:74:21)
    at StoreService.create (C:\Users\dchir\Projects\Empire-CLI\dist\services\StoreService.js:24:52)
    at Command.<anonymous> (C:\Users\dchir\Projects\Empire-CLI\dist\Actions.js:99:55)
    at step (C:\Users\dchir\Projects\Empire-CLI\dist\Actions.js:33:23)
    at Object.next (C:\Users\dchir\Projects\Empire-CLI\dist\Actions.js:14:53)
    at C:\Users\dchir\Projects\Empire-CLI\dist\Actions.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\dchir\Projects\Empire-CLI\dist\Actions.js:4:12)
    at Command.createStoreAndWriteFileSystem (C:\Users\dchir\Projects\Empire-CLI\dist\Actions.js:93:12)

```

**Comment by d-chirkov** [comment]
Проблема в том, что при поиска файла в архиве путь начинается со слэша, в то время как реальный путь без слэша.

Вот тут первый метод указан верно:

```
    ArchiveProvider.prototype.getKeysFileContentTemplate = function () {
        return this.getContentTemplateByFileName("store/keys.txt");
    };
    ArchiveProvider.prototype.getActionsContentTemplate = function () {
        return this.getContentTemplateByFileName("/store/actions.txt");
    };
    ArchiveProvider.prototype.getActionsTypeContentTemplate = function () {
        return this.getContentTemplateByFileName("/store/actions.type.txt");
    };
    ArchiveProvider.prototype.getReducersContentTemplate = function () {
        return this.getContentTemplateByFileName("/store/reducers.txt");
    };
    ArchiveProvider.prototype.getReducersTestContentTemplate = function () {
        return this.getContentTemplateByFileName("/store/reducers.test.txt");
    };
    ArchiveProvider.prototype.getStateContentTemplate = function () {
        return this.getContentTemplateByFileName("/store/state.txt");
    };
```

**Comment by MrMurdock11** [comment]
Исправлено в версии пакета "1.0.3".
